baseurl = "/"
languageCode = "en-us"
title = "Jessica Huynh"

pluralizeListTitles = false

[params]
	subtitle = "/hwÉªn/"
	categories = ["jessicahuynh.info","Web development","WordPress"]
	kinds = ["post","status"]
	
[taxonomies]
	project = "projects"
	tag = "tags"
	category = "categories"
	kind = "kinds"
	
[[menu.main]]
	name = "about"
	identifier = "about"
	url = "/about"
	weight = -100
[[menu.main]]
	name = "portfolio"
	identifier = "portfolio"
	url = "/portfolio"
	weight = -80
[[menu.main]]
	name = "blog"
	identifier = "blog"
	url = "/blog"
	weight = -70
[[menu.main]]
	name = "contact"
	identifier = "contact"
	url = "/contact"
	weight = -60