[build]
    publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_VERSION = "0.72.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[[redirects]]
    from = "https://jessicahuynh.netlify.app/*"
    to = "https://www.jessicahuynh.info/:splat"
    status = "301!"

[[redirects]]
    from = "/blog/:year/:month/"
    to = "/archive/#:year"
    status = 301

[[redirects]]
    from = "/blog/:year"
    to = "/archive/#:year"
    status = 301
