[build]
    publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_VERSION = "0.72.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[[redirects]]
    from = "/archive/:year/:month/"
    to = "/archive/#:year"
    status = 301

[[redirects]]
    from = "/archive/:year"
    to = "/archive/#:year"
    status = 301
