[build]
    publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_VERSION = "0.72.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[[redirects]]
    /archive/:year/:month/ /archive/#:year
    /archive/:year /archive/#:year
